[project]
name = "evoconnect4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "unmeel.banerjea", email = "unmeel@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.2",
    "pyyaml>=6.0.3",
]

[project.scripts]
evoconnect4 = "evoconnect4:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
